# Generated by Django 6.0 on 2026-01-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
