# Generated by Django 6.0 on 2026-01-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_page_alter_servicio_duracion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
